version: '3.8'

networks:
  minha_rede:
    driver: bridge
services:
  db:
    container_name: avenant-db
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=avenant
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/dbdata
    networks:
      - minha_rede

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  api:
    container_name: avenant-api
    build: 
      context: ./backend
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
      - "5555:5555"
    networks:
      - minha_rede
    env_file:
    - ./backend/.env

  web:
    container_name: avenant-web
    build:
      context: ./frontend
    depends_on:
      - api
    ports:
      - "5173:5173" 
    networks:
      - minha_rede
